spring:
  application:
    name: spring-message-kafka

  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092

    template:
      default-topic: kafka-topic

    # 设置消费者组名
    consumer:
      group-id: yangzl
