

spring:

  application:
    name: spring-message-jms

  activemq:
    broker-url: localhost:61616
    in-memory: false

  artemis:
    host: localhost
    port: 61616

  jms:
    template:
      default-destination: jms.queue.default