spring:
  application:
    name: spring-dao

  # spring 异步任务线程池配置
  task:
    execution:
      pool:
        core-size: 8
        max-size: 64
        queue-capacity: 512

  # spring 调度任务线程池配置
    scheduling:
      pool:
        size: 2

  datasource:
    # 默认配置 >> HikariConfig
    hikari:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/yangzl?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=GMT&allowMultiQueries=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.yangzl.spring.entity


server:
  port: 10001
