

server:
  port: 8000
  servlet:
    context-path: /reactor

spring:
  application:
    name: spring-reactor

  main:
    web-application-type: reactive

  data:
    mongodb:
      host: localhost
      port: 27017
      database: tacoclouddb